version: "3.4"
services:
  nfc_scrapper:
    build: .
    command: npm run dev
    container_name: nfc_scrapper_node
    environment:
      - PORT=3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 3031:3000
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    image: postgres:11.2-alpine
    container_name: nfc_scrapper_postgres
    ports:
      - 5434:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    container_name: nfc_scrapper_redis
    image: redis:5.0.4-alpine
    command: --databases 6000
    ports:
      - 6381:6379
    restart: unless-stopped
    volumes:
      - redis-data:/var/lib/redis

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
