version: "3.4"
services:
  nfc_scrapper:
    build: .
    command: npm run dev
    container_name: nfc_scrapper_node
    environment:
      - PORT=3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 3031:3000
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    container_name: nfc_scrapper_postgres
    ports:
      - 5434:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
    driver: local
